#!/bin/bash -l
#PBS -l walltime=24:00:00,nodes=1:ppn=12,mem=32GB
#PBS -m abe
#PBS -M adamo010@umn.edu
#PBS -q blekhman

module load kallisto
kallisto quant -i ~/Mayo_RNAseq_project/human_transcriptome.idx -b 100 -o ~/Mayo_RNAseq_project/Apc_tg_il23R_Ho_CN_11_S10_output /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_tg_il23R_Ho_CN_11_S10_R1_001.fastq.gz /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_tg_il23R_Ho_CN_11_S10_R2_001.fastq.gz

kallisto quant -i ~/Mayo_RNAseq_project/human_transcriptome.idx -b 100 -o ~/Mayo_RNAseq_project/Apc_tg_il23R_Ho_CN_15_S14_output /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_tg_il23R_Ho_CN_15_S14_R1_001.fastq.gz /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_tg_il23R_Ho_CN_15_S14_R2_001.fastq.gz

kallisto quant -i ~/Mayo_RNAseq_project/human_transcriptome.idx -b 100 -o ~/Mayo_RNAseq_project/Apc_tg_il23R_Ho_CN_3_S3_output /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_tg_il23R_Ho_CN_3_S3_R1_001.fastq.gz /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_tg_il23R_Ho_CN_3_S3_R2_001.fastq.gz

kallisto quant -i ~/Mayo_RNAseq_project/human_transcriptome.idx -b 100 -o ~/Mayo_RNAseq_project/Apc_tg_il23R_Ho_CN_7_S7_output /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_tg_il23R_Ho_CN_7_S7_R1_001.fastq.gz /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_tg_il23R_Ho_CN_7_S7_R2_001.fastq.gz

kallisto quant -i ~/Mayo_RNAseq_project/human_transcriptome.idx -b 100 -o ~/Mayo_RNAseq_project/Apc_tg_il23R_Ho_CP_12_S11_output /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_tg_il23R_Ho_CP_12_S11_R1_001.fastq.gz /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_tg_il23R_Ho_CP_12_S11_R2_001.fastq.gz

kallisto quant -i ~/Mayo_RNAseq_project/human_transcriptome.idx -b 100 -o ~/Mayo_RNAseq_project/Apc_tg_il23R_Ho_CP_16_S15_output /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_tg_il23R_Ho_CP_16_S15_R1_001.fastq.gz /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_tg_il23R_Ho_CP_16_S15_R2_001.fastq.gz

kallisto quant -i ~/Mayo_RNAseq_project/human_transcriptome.idx -b 100 -o ~/Mayo_RNAseq_project/Apc_tg_il23R_Ho_CP_4_S4_output /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_tg_il23R_Ho_CP_4_S4_R1_001.fastq.gz /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_tg_il23R_Ho_CP_4_S4_R2_001.fastq.gz

kallisto quant -i ~/Mayo_RNAseq_project/human_transcriptome.idx -b 100 -o ~/Mayo_RNAseq_project/Apc_tg_il23R_Ho_CP_8_S8_output /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_tg_il23R_Ho_CP_8_S8_R1_001.fastq.gz /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_tg_il23R_Ho_CP_8_S8_R2_001.fastq.gz
