#!/bin/bash -l
#PBS -l walltime=24:00:00,nodes=1:ppn=12,mem=32GB
#PBS -m abe
#PBS -M adamo010@umn.edu
#PBS -q blekhman

module load kallisto
kallisto quant -i ~/Mayo_RNAseq_project/human_transcriptome.idx -b 100 -o ~/Mayo_RNAseq_project/Apc_TG_CN_30_S29_output /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_CN_30_S29_R1_001.fastq.gz /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_CN_30_S29_R2_001.fastq.gz

kallisto quant -i ~/Mayo_RNAseq_project/human_transcriptome.idx -b 100 -o ~/Mayo_RNAseq_project/Apc_TG_CP_20_S19_output /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_CP_20_S19_R1_001.fastq.gz /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_CP_20_S19_R2_001.fastq.gz

kallisto quant -i ~/Mayo_RNAseq_project/human_transcriptome.idx -b 100 -o ~/Mayo_RNAseq_project/Apc_TG_CP_24_S23_output /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_CP_24_S23_R1_001.fastq.gz /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_CP_24_S23_R2_001.fastq.gz

kallisto quant -i ~/Mayo_RNAseq_project/human_transcriptome.idx -b 100 -o ~/Mayo_RNAseq_project/Apc_TG_CP_31_S30_output /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_CP_31_S30_R1_001.fastq.gz /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_CP_31_S30_R2_001.fastq.gz

kallisto quant -i ~/Mayo_RNAseq_project/human_transcriptome.idx -b 100 -o ~/Mayo_RNAseq_project/Apc_TG_SN_17_S16_output /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_SN_17_S16_R1_001.fastq.gz /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_SN_17_S16_R2_001.fastq.gz

kallisto quant -i ~/Mayo_RNAseq_project/human_transcriptome.idx -b 100 -o ~/Mayo_RNAseq_project/Apc_TG_SN_21_S20_output /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_SN_21_S20_R1_001.fastq.gz /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_SN_21_S20_R2_001.fastq.gz