#!/bin/bash -l
#PBS -l walltime=24:00:00,nodes=1:ppn=12,mem=32GB
#PBS -m abe
#PBS -M adamo010@umn.edu
#PBS -q blekhman

module load kallisto
kallisto quant -i ~/Mayo_RNAseq_project/human_transcriptome.idx -b 100 -o ~/Mayo_RNAseq_project/Apc_TG_SP_29_S28_output /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_SP_29_S28_R1_001.fastq.gz /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_SP_29_S28_R2_001.fastq.gz

kallisto quant -i ~/Mayo_RNAseq_project/human_transcriptome.idx -b 100 -o ~/Mayo_RNAseq_project/Apc_TG_SP_26_S25_output /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_SP_26_S25_R1_001.fastq.gz /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_SP_26_S25_R2_001.fastq.gz

kallisto quant -i ~/Mayo_RNAseq_project/human_transcriptome.idx -b 100 -o ~/Mayo_RNAseq_project/Apc_TG_SP_22_S21_output /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_SP_22_S21_R1_001.fastq.gz /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_SP_22_S21_R2_001.fastq.gz

kallisto quant -i ~/Mayo_RNAseq_project/human_transcriptome.idx -b 100 -o ~/Mayo_RNAseq_project/Apc_TG_SP_18_S17_output /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_SP_18_S17_R1_001.fastq.gz /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_SP_18_S17_R2_001.fastq.gz

kallisto quant -i ~/Mayo_RNAseq_project/human_transcriptome.idx -b 100 -o ~/Mayo_RNAseq_project/Apc_TG_SN_28_S27_output /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_SN_28_S27_R1_001.fastq.gz /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_SN_28_S27_R2_001.fastq.gz

kallisto quant -i ~/Mayo_RNAseq_project/human_transcriptome.idx -b 100 -o ~/Mayo_RNAseq_project/Apc_TG_SN_25_S24_output /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_SN_25_S24_R1_001.fastq.gz /home/blekhman/data_release/umgc/novaseq/200401_A00223_0352_AH75N7DSXY/Blekhman_Project_037/Apc_TG_SN_25_S24_R2_001.fastq.gz